- name: Get running gunicorn
  shell: "ps -ef | grep -v grep | grep -w gunicorn | awk '{print $2}'"
  register: gunicorn

# Killing the first one is usually enough
- name: Kill first unning gunicorn
  shell: "kill {{ item }} 2>&1 > /dev/null"
  with_items: "{{ gunicorn.stdout_lines.0 }}"
  become: yes
  ignore_errors: yes
  when: gunicorn.stdout_lines.0 is defined

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ gunicorn.stdout_lines.0 }}"
  ignore_errors: yes
  when: gunicorn.stdout_lines.0 is defined

- name: Get remaining running gunicorn
  shell: "ps -ef | grep -v grep | grep -w gunicorn | awk '{print $2}'"
  register: gunicorn

- name: Kill all running gunicorn
  shell: "kill {{ item }} 2>&1 > /dev/null"
  with_items: "{{ gunicorn.stdout_lines }}"
  become: yes
  ignore_errors: yes
  when: gunicorn.stdout_lines is defined and (gunicorn.stdout_lines|length>0)

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ gunicorn.stdout_lines }}"
  ignore_errors: yes
  register: killed
  when: gunicorn.stdout_lines is defined and (gunicorn.stdout_lines|length>0)

- name: Force kill stuck processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed.results | select('failed') | map(attribute='item') | list }}"
  become: yes
  when: killed.results is defined and and (killed.results|length>0)

- name: Remove app directory 
  file:
    path: /app/
    state: absent
  become: yes