---
- name: Verify that the latest Red Hat Subscription Manager is present
  yum:
    name: subscription-manager
    state: latest

- name: Register system into RHSM
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    force_register: yes

- name: Add the EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    
- name: Install needed packages
  yum:
    name: [ python-pip, unzip, libXext, libSM, libXrender, firewalld ]
    state: present

- name: Configure firewalld 
  systemd: 
    name: firewalld 
    masked: no  
    enabled: yes
    state: restarted

- name: Open firewall for http
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  with_items: 
    - 80

# - name: Register with Red Had Insight
#   command: redhat-access-insights --register

- name: Update pip and setup tools
  pip:
    name: [ pip, setuptools ]
    extra_args: --upgrade   
  become: yes
